fn main() {
    sync_code::Builder::new()
        .add("src/uart/usart2.rs", "src/uart/usart1.rs")
        .add("src/uart/usart3.rs", "src/uart/usart1.rs")
        .add("src/uart/uart4.rs", "src/uart/usart1.rs")
        .add("src/uart/uart5.rs", "src/uart/uart4.rs")
        .add("src/timer/timer2.rs", "src/timer/timer1.rs")
        .add("src/timer/timer3.rs", "src/timer/timer2.rs")
        .add("src/timer/timer4.rs", "src/timer/timer2.rs")
        .add("src/timer/timer5.rs", "src/timer/timer2.rs")
        .add("src/timer/timer6.rs", "src/timer/timer1.rs")
        .add("src/timer/timer7.rs", "src/timer/timer6.rs")
        .add("src/timer/timer8.rs", "src/timer/timer1.rs")
        .add("src/timer/timer9.rs", "src/timer/timer1.rs")
        .add("src/timer/timer10.rs", "src/timer/timer1.rs")
        .add("src/timer/timer11.rs", "src/timer/timer10.rs")
        .add("src/timer/timer12.rs", "src/timer/timer9.rs")
        .add("src/timer/timer13.rs", "src/timer/timer10.rs")
        .add("src/timer/timer14.rs", "src/timer/timer10.rs")
        .add("src/timer/timer15.rs", "src/timer/timer9.rs")
        .add("src/timer/timer16.rs", "src/timer/timer10.rs")
        .add("src/timer/timer17.rs", "src/timer/timer10.rs")
        .add("src/i2c/i2c2.rs", "src/i2c/i2c1.rs")
        .sync();
}
